services:
   _defaults:
      autowire: true
      autoconfigure: true
      public: false

   WEBcoast\DeferredImageProcessing\:
        resource: '../Classes/*'
        exclude: '../Classes/Event/*'
